import typer
from pathlib import Path
from agri_data_gen.core.data_access.taxonomy_manager import TaxonomyManager
from agri_data_gen.core.generators.generator import GenerationEngine
from agri_data_gen.core.knowledge.bundle_builder import BundleBuilder
from agri_data_gen.gemini_batch_processing.create_job import TextBatchJob

app = typer.Typer()



@app.command()
def load_taxonomies(taxonomy_dir: str = "sample_data/taxonomies"):
    """
    Loads taxonomy schemas into MongoDB and prints a summary.
    """

    print("Loading taxonomies...")
    manager = TaxonomyManager()
    manager.load_from_files_and_store(taxonomy_dir)

    taxonomies = manager.get_active_taxonomies()
    print(f"\nLoaded {len(taxonomies)} active taxonomies:\n")

    for t in taxonomies:
        print(f"Group: {t['group']}")
        print(f"  Attributes: {len(t['attributes'])}")
        print(f"  Entries: {len(t['entries'])}")
        print("-" * 40)

@app.command()
def reset_taxonomies():
    """
    Completely clears the taxonomy collection in MongoDB.
    Use before reloading taxonomies after schema changes.
    """
    manager = TaxonomyManager()
    deleted = manager.reset_taxonomy_collection()
    print(f"Deleted {deleted} taxonomy entries.")


@app.command()
def batch_run(bundle_file: str = "data/bundles/bundles.jsonl"):
    """
    Submits the generated bundles to Google Batch API (Cheaper/Faster).
    """
    
    print(f"🚀 Submitting Batch Job for: {bundle_file}")
    
    processor = TextBatchJob()
    # Pass the exact same file path generated by BundleBuilder
    processor.create_jsonl(bundle_file) 
    processor.submit_job()
    
    print("Job Submitted. Use separate monitor command to check status.")


@app.command()
def pipeline_run(
    bundle_dir: str = "data/bundles", 
    output_dir: str = "data/generated",
    bundle_filename: str = "bundles.jsonl",
    output_filename: str = "data.jsonl",
    limit: int = None
):
    """
    Run the full end-to-end pipeline:
    taxonomies → bundles → generation
    """

    print("Starting end-to-end pipeline...")

    # Build bundles
    print("Building bundles...")
    bundle_builder = BundleBuilder(out_dir=bundle_dir)
    bundle_builder.load_all()
    generated_bundles_path = bundle_builder.build_all(filename= bundle_filename)

    # Generate data from bundles
    print("Generating reasoning data...")
    output_file = Path(output_dir)/output_filename
    engine = GenerationEngine(bundle_file=generated_bundles_path, out_file=output_file)
    engine.generate_all(limit=limit)

    print("Pipeline completed successfully.")


def main():

    app()

if __name__ == "__main__":
    main()
